routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'reset' => false,
    'confirm' => false,
    'verify' => false,
    'register' => false,
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', function () {
    return view('guest.index', ['data' => (new \App\Models\hospital)->index()]);
})->name('index');

Route::get('/find', function () {
    return view('guest.find');
})->name('find');

Route::get('/find/result', function (Request $request) {
    return view('guest.find', ['data' => (new \App\Models\hospital)->find($request->input('name'))]);
})->name('show');
Route::middleware(['auth'])->group(function () {
    Route::resource('admin/bolnoy', 'App\Http\Controllers\AdminController', ['parameters' => [
        'bolnoy' => 'id'
    ]]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/diagnoz.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class diagnoz extends Model
{
    protected $table = "diagnoz";
    public function diagnozes(){
        return DB::table('diagnoz')->get();
    }
}

app/Models/hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class hospital extends Model
{
    protected $table = "hospital";

    public function index()
    {
        return DB::table('hospital')
            ->join('diagnoz as b', 'b.id', '=', 'hospital.bolezn')
            ->select('hospital.*', 'b.diagnoz as b_diagnoz')
            ->orderBy('hospital.id')
            ->get();

    }

    public function find($name)
    {
        return DB::table('hospital', 'h')
            ->join('diagnoz as b', 'b.id', '=', 'h.bolezn')
            ->select('h.*', 'b.diagnoz as b_diagnoz')
            ->where('h.l_name', $name)->get();
    }

    public function show($id)
    {
        return DB::table('hospital', 'h')
            ->join('diagnoz as b', 'b.id', '=', 'h.bolezn')
            ->select('h.*', 'b.diagnoz as b_diagnoz')
            ->where('h.id', $id)->get();
    }
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Models\hospital;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.index', ['data' => (new \App\Models\hospital)->index()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.add', ['boleznes' => (new \App\Models\diagnoz)->diagnozes()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $add = new hospital();
        $add->l_name = $request->input('name');
        $add->date_hosp = $request->input('date');
        $add->palata_id = $request->input('palata');
        $add->bolezn = $request->input('diagnoz');
        $add->save();
        return redirect()->route('bolnoy.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.find', ['data' => (new \App\Models\hospital)->show($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.edit', ['result' => (new \App\Models\hospital)->show($id),
            'boleznes' => (new \App\Models\diagnoz)->diagnozes()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::table('hospital')
            ->where('id', $id)
            ->update([
                'l_name' => $request->input('name'),
                'date_hosp' => $request->input('date'),
                'palata_id' => $request->input('palata'),
                'bolezn' => $request->input('diagnoz')]);
        return redirect()->route('bolnoy.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('hospital')->where('id', '=', $id)->delete();
        return redirect()->route('bolnoy.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/add.blade.php
@extends('admin.app.schema')
@section('title','Add')

@section('content')

    <h1>Введіть інформацію про хворобу</h1>
<form action="{{route('bolnoy.store')}}" method="post">
    @csrf
    <p>
        <label for="diagnoz">Назва хвороби</label>
        <select id="diagnoz" name="diagnoz" required>
            @foreach($boleznes as $bolezn)
                <option value='{{ $bolezn->id }}'>{{ $bolezn->diagnoz }}</option>
            @endforeach
        </select>
    </p>
    <p>
        <label for = "name">Iм`я хворого</label>
        <input type="text" placeholder="Введіть Iм`я" id="name" name="name" required>
    </p>
    <p>
        <label for="palata">Номер палати</label>
        <input type="text" placeholder="Введіть номер палати" id="palata_id" name="palata" required>
    </p>
    <p>
        <label for="diagnoz">Дата госпіталізації</label>
        <input type="date" placeholder="Введіть дату госпіталізації" id="date_hosp" name="date" required>
    </p>
    <p>
        <button type="submit">Додати</button>
    </p>
</form>
@endsection

resources/views/admin/app/schema.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
</head>
<body>
@yield('content')
@if(isset($data))
@foreach ($data as $row)
<p>
    ID:   {{$row->id}}
</p>
<p>
    Iм`я: {{$row->l_name}}
</p>
<p>
    Номер кiмнати: {{$row->palata_id}}
</p>
<p>
    Дата коли поступив пацiэнт: {{$row->date_hosp}}
</p>
<p>
    Хвороба: {{$row->b_diagnoz}}
</p>

<a href="{{route('bolnoy.edit',['id' => $row->id]) }}"
    >Редагувати</a>
<form action="{{ route('bolnoy.destroy' , $row->id)}}" method="POST">
    <input name="_method" type="hidden" value="DELETE">
    {{ csrf_field() }}
    <button type="submit">Видалити</button>
</form>

------------------------------------------------------------------------------------------
@endforeach
    @endif
</body>
</html>

resources/views/admin/edit.blade.php
@extends('admin.app.schema')
@foreach($result as $res)
@section('title','Edit' .$res->l_name)

@section('content')

    <h1>Введіть інформацію про хворобу</h1>
    <form action="{{route('bolnoy.update', ['id' => $res->id] )}}" method="post">
        <input name="_method" type="hidden" value="PUT">
        @csrf
        <p>
            <label for="diagnoz">Назва хвороби</label>
            <select id="diagnoz" name="diagnoz" required>
                @foreach($boleznes as $bolezn)
                    <option value='{{ $bolezn->id }}'>{{ $bolezn->diagnoz }}</option>
                @endforeach
            </select>
        </p>

        <p>
            <label for = "name">Iм`я хворого</label>
            <input value="{{$res->l_name}}" type="text" placeholder="Введіть Iм`я" id="name" name="name" required>
        </p>

        <p>
            <label for="palata">Номер палати</label>
            <input value="{{$res->palata_id}}" type="text" placeholder="Введіть номер палати" id="palata_id" name="palata" required>
        </p>

        <p>
            <label for="diagnoz">Дата госпіталізації</label>
            <input value="{{$res->date_hosp}}" type="date" placeholder="Введіть дату госпіталізації" id="date_hosp" name="date" required>
        </p>

        <p>
            <button type="submit">Редагувати</button>
        </p>
    </form>
@endsection
@endforeach

resources/views/admin/index.blade.php
@extends('admin.app.schema')
@section('title','Main')

@section('content')
    <p>
{{--        <a href="{{route('bolnoy.show')}}">Пошук</a>\--}}
        <a href="{{route('bolnoy.create')}}">Додати</a>\
        <a class="dropdown-item" href="{{ route('logout') }}"
           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
        @csrf
    </form>
    </p>
@endsection

resources/views/guest/app/schema.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
</head>
<body>
@yield('content')
@if(isset($data))
@foreach ($data as $row)
<p>
    ID:   {{$row->id}}
</p>
<p>
    Iм`я: {{$row->l_name}}
</p>
<p>
    Номер кiмнати: {{$row->palata_id}}
</p>
<p>
    Дата коли поступив пацiэнт: {{$row->date_hosp}}
</p>
<p>
    Хвороба: {{$row->b_diagnoz}}
</p>

------------------------------------------------------------------------------------------
@endforeach
    @endif
</body>
</html>

resources/views/guest/find.blade.php
@extends('guest.app.schema')
@section('content')
    <form  action="{{route('show')}}">
        @csrf
    <p>
        <input type="text" name="name">
        <button type="submit">Пошук</button>
            <a href="{{route('index')}}">Назад</a>
    </p>
    </form>
@endsection

resources/views/guest/index.blade.php
@extends('guest.app.schema')
@section('title','Main')

@section('content')
    <p>
        <a href="{{route('find')}}">Пошук</a>\
        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
    </p>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>